#Numpy Tutorial

In [1]:
import numpy as np

# 1. declaring a numpy array

In [2]:
arr1 = np.array([1,2,3,4]) #easiest way to declare a numpy array.

In [3]:
print(arr1)

[1 2 3 4]


# 2. arr.shape

In [6]:
arr1.shape #it returns the following (no of rows, no of columns)

(4,)

# 3. arr.dtype

In [7]:
arr1.dtype

dtype('int64')

# Array Creation : Conversion from other Python Structures

In [11]:
listarray = np.array([[1,2,3], [4,5,6], [7,8,9]]) #conversion from array

In [10]:
print(listarray)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


# Array Creation : Making a list of length "n" with all elements = 0

In [17]:
listarray = np.zeros((2,5)) #array with 2 sub array containing 5 elements each.

In [18]:
print(listarray)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


# Array Creation : Creates an array from 0 to "n-1"

In [15]:
newarray = np.arange(15)

In [16]:
print(newarray)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


# Array Creation : Creates an array from i to j with equal spaces between numbers and gives k numbers.

In [21]:
newarray1 = np.linspace(1,2,12) #i = 1, j = 2, k = 12

In [22]:
print(newarray1)

[1.         1.09090909 1.18181818 1.27272727 1.36363636 1.45454545
 1.54545455 1.63636364 1.72727273 1.81818182 1.90909091 2.        ]


# Array Creation : Creates an array with random elements

In [23]:
newarray2 = np.empty([4,6]) #creates an array with 4 sub arrays with 6 elements each

In [24]:
print(newarray2)

[[6.95229613e-310 6.95229611e-310 0.00000000e+000 5.00791007e-312
  1.22075699e-311 4.94065646e-324]
 [0.00000000e+000 0.00000000e+000 4.04738577e-320 0.00000000e+000
  1.23022346e-321 1.22079578e-311]
 [3.56043054e-307 1.37961641e-306 0.00000000e+000 1.22079579e-311
  1.78020169e-306 7.56601165e-307]
 [1.02359984e-306 4.99006302e-322 2.22522597e-306 8.01097889e-307
  2.22522597e-306             nan]]


# Array Creation : Creates an empty array with size of passed array.

In [25]:
newarray3 = np.empty_like(newarray2)

In [26]:
print(newarray3)

[[6.95229613e-310 6.95229611e-310 0.00000000e+000 5.00791007e-312
  1.22075699e-311 4.94065646e-324]
 [0.00000000e+000 0.00000000e+000 4.04738577e-320 0.00000000e+000
  1.23022346e-321 1.22080115e-311]
 [1.37961641e-306 9.45697982e-308 0.00000000e+000 1.22080115e-311
  7.56601165e-307 1.02359984e-306]
 [1.33510679e-306 5.78056806e-322 8.01097889e-307 1.42419666e-306
  6.89810583e-307             nan]]


# Array Creation : Creating a random array with dimensions = N * N

In [27]:
newarray4 = np.identity(3)

In [28]:
print(newarray4)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# Reshaping the array created from arange

In [29]:
arrnew = np.arange(15)

In [33]:
arrnew = arrnew.reshape(3,5)

In [34]:
print(arrnew)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


# Converting a reshaped array into its original form

In [41]:
arrnew = arrnew.ravel()

In [42]:
print(arrnew)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


# Axis in numpy

In [44]:
array1 = ([[1,2,3], [4,5,6], [7,8,9]])

In [45]:
ar = np.array(array1)

In [46]:
print(ar)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [47]:
ar.sum(axis = 0)

array([12, 15, 18])

In [48]:
ar.sum(axis = 1)

array([ 6, 15, 24])

# Transpose of an array

In [50]:
ar.T #it returns the transpose of an array

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

# Getting all elements of an array

In [52]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
8
9


# To get number of dimensions

In [53]:
ar.ndim

2

# To get number of elements in the array

In [54]:
ar.size

9

# To get total space consumed by elements of an array

In [57]:
ar.nbytes

72

# Min, Max, Sorted array index positions

In [59]:
newarr1 = [1,20,12,13,29,111]

In [60]:
ar1 = np.array(newarr1)

In [61]:
ar1.argmax()

np.int64(5)

In [62]:
ar1.argmin()

np.int64(0)

In [63]:
ar1.argsort()

array([0, 2, 3, 1, 4, 5])

In [64]:
# for a 2d array

In [65]:
ar.argmin()

np.int64(0)

In [66]:
ar.argmax()

np.int64(8)

In [67]:
ar.argmax(axis = 0)

array([2, 2, 2])

In [68]:
ar.argmin(axis = 0)

array([0, 0, 0])

In [69]:
ar.argsort(axis = 0)

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2]])

# Addition and Multiplication of a matrix

In [78]:
ar01 = ([[0,1,2]]) 
ar02 = ([[3,4,5]])
arrr1 = np.array(ar01)
arrr2 = np.array(ar02)

In [79]:
arrr1 * arrr2

array([[ 0,  4, 10]])

In [80]:
arrr1 + arrr2

array([[3, 5, 7]])

# Square root of all indivisual elements of a matrix

In [81]:
np.sqrt(arrr1)

array([[0.        , 1.        , 1.41421356]])

# Misc operations

In [85]:
arrr1.sum()

np.int64(3)

In [88]:
np.where(arrr1>1)

(array([0]), array([2]))

In [90]:
np.count_nonzero(arrr1) #counts non zero elements of an array

2